- package.json
- src/components/user_management/UserManagement.js
- src/services/services.js
> fleshing out user management page

- src/components/CopyButton.js
- src/components/user_management/UserManagement.js
- src/style.css
add processing icon
add deletion, key rotation sections
adding copy button
> Manage user updates

- src/components/user_management/UserManagement.js
- src/services/apiClient.js
use versioned service
update usermanagement ui to use service returned value 
update usermanagement ui to use spinner state on revoke button
> User Management tweaks

- src/components/sites/Site.js
- src/components/sites/SiteManagement.js
- src/components/sites/newSiteDialog.js
- src/components/user_management/UserManagement.js
add site deletion
add new site creation QOL improvements
> updating site operations

- package-lock.json
- package.json
- src/App.js
- src/components/Home/Home.js
move Home component
move react-scripts to dev dependency
> clean up security + project layout

- src/components/Home/TimeSeries.js
- src/services/apiClient.js
- src/services/search.js
- src/services/services.js
adding temp OpenSearch scaffolding (to be moved to lambda)
> adding first rough of timeseries graph

- src/components/Home/MetricsTile.js
- src/components/Home/TimeSeries.js
- src/components/dashboards/Dashboard.js
- src/components/sites/Device.js
- src/components/sites/NewDeviceDialog.js
- src/components/sites/Site.js
- src/components/sites/SiteAttributes.js
- src/components/sites/SiteManagement.js
- src/services/search.js
- src/style.css
add more mobile friendly styles
fix bugs w/setting bad values in device forms
fix bug w/no display name for devices
use real services by default
fix bug w/not displaying devices for that have no site
fix bug w/displaying site delete button for no site
push deviceId w/search json so we can move to query by id instead of name
> Mobile friendly updates

- src/components/UserMenu.js
- src/components/sites/SiteManagement.js
- src/style.css
disabled button wasn't look top notch
site management use sticky state
> footer was showing in wrong text color

- src/App.js
- src/components/Home/Home.js
- src/components/Navbar.js
- src/components/checkout/CheckoutReturn.js
- src/components/dashboards/Dashboard.js
- src/components/reports/Reports.js
- src/components/sites/SiteManagement.js
- src/components/user_management/UserManagement.js
- src/services/apiClient.js
- src/services/services.js
add customer deletion
add pricing redirect
add global error handling
> acct managment changes

- src/components/checkout/CheckoutForm.js
- src/components/checkout/CheckoutReturn.js
- src/components/user_management/UserManagement.js
- src/services/services.js
move status to proper service call via axios
> add loading status/components to billing locations

- src/components/Footer.js
- src/components/Home/Home.js
- src/components/alarms/Alarms.js
- src/components/dashboards/Dashboard.js
- src/components/reports/Reports.js
- src/components/sites/Site.js
- src/components/sites/SiteManagement.js
- src/components/user_management/ChangePassword.js
- src/components/user_management/ManagePlanTile.js
- src/components/user_management/UserManagement.js
- src/services/services.js
- src/style.css
add min height to all base pages
update icon styling to be consistent
add icon to password change button
add subscription information to billing page pre going to billing portal
> Adding current plan tile

- package-lock.json
- package.json
- src/App.js
- src/components/graphs/FormattedLabel.js
- src/components/graphs/MetricsTile.js
- src/components/reports/Reports.js
- yarn.lock
Also provide foundation for multilanguage support
> add some number formatting to display so larger numbers are more legible

- src/components/sites/SiteManagement.js
add subscription check for add device/site buttons
> add sorting of site list

- src/components/dashboards/Dashboard.js
- src/components/reports/SearchBar.js
- src/components/sites/Device.js
- src/components/sites/Site.js
- src/components/sites/SiteManagement.js
- src/style.css
- src/utils/Utils.js
refactor device sorting to utility function
add ability to disable devices
> Add disabled devices

- src/components/UserMenu.js
- src/components/checkout/PricingPage.js
> update value props on pricing page

- src/components/alarms/Alarms.js
- src/components/reports/Reports.js
- src/components/reports/SearchBar.js
add refresh button to search bar
reset device if changing active site search so we don't deadend users
> Search ux updates

- .github/workflows/deploy.yml
push to dev.solarmoonanalytics on new code
> change branch to master

- src/components/graphs/MetricsTile.js
- src/services/search.js
- src/services/services.js
remove direct OS api
use combined search for tile
> add weather display to tiles

- src/components/views/site-list/SiteList.jsx
- src/components/views/site-list/SiteRow.jsx
fixes: https://github.com/bigboxer23/solar-moon-frontend/issues/151
> Show active alerts on site list

- src/components/views/dashboard/Overview.js
- src/components/views/dashboard/OverviewChart.js
- src/components/views/site-details/DeviceChart.js
- src/components/views/site-details/SiteDetails.js
- src/components/views/site-details/SiteDetailsGraph.js
- src/utils/Utils.js
fix: tweak date display on graphs to have proper starting date
refactor: tooltip date to use standard date formatting function
> fix: tweak date range display to drop leading 0

- src/components/common/Check.js
- src/components/common/Input.js
- src/components/common/Modal.js
- src/components/common/Select.js
- src/components/views/checkout/PriceTile.js
- src/components/views/checkout/PricingPage.js
- src/components/views/profile/ManagePlanTile.jsx
switch colors to make them consistent
> Gray -> Neutral

- src/components/views/site-details/DeviceChart.js
- src/components/views/site-details/SiteDetailsGraph.js
> fix: fix issue w/incomplete data causing exception in tooltip of graph

- src/components/common/StackedStatBlock.jsx
- src/components/common/StatBlock.js
- src/components/device-block/StackedAlertsInfo.js
- src/components/views/site-details/SiteDetails.js
- src/components/views/site-details/SiteDevicesOverview.js
fix: dark theme stat block display embed in component
> fix: dark theme display of stacked stat block

- src/components/common/CurrentPowerBlock.jsx
- src/components/common/PowerBlock.jsx
- src/components/common/StatBlock.js
- src/components/common/WeatherBlock.js
- src/components/device-block/DeviceBlock.js
- src/components/device-block/StackedAlertsInfo.js
- src/components/device-block/StackedTotAvg.js
- src/components/views/dashboard/Overview.js
- src/components/views/dashboard/OverviewSiteList.js
- src/components/views/site-details/SiteDetails.js
- src/components/views/site-details/SiteDevicesOverview.js
- tailwind.config.js
> Rework Site/Overview stat display

- src/components/device-block/DeviceBlock.js
- src/components/device-block/StackedCurrentVoltageBlock.jsx
- src/components/views/site-details/SiteDevicesOverview.js
feat: remove expand/contract on devices if not on mobile
> feat: hide voltage/current if missing either piece
